"""
Script to generate standard Jupyter Notebooks (.ipynb) for the Statistics Laboratory Experiments.
Creates interactive notebooks with markdown theory, equations, Python code, and visual plots.
"""
import json
import os

NOTEBOOKS_DIR = os.path.dirname(__file__)


def make_notebook(title: str, cells: list[dict]) -> dict:
    return {
        "cells": cells,
        "metadata": {
            "language_info": {"name": "python", "version": "3.11"},
            "orig_nbformat": 4,
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }


def md_cell(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [line + "\n" for line in source.strip().split("\n")]
    }


def code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [line + "\n" for line in source.strip().split("\n")]
    }


# -------------------------------------------------------------
# 1. 01_eda_descriptive_stats.ipynb
# -------------------------------------------------------------
nb1_cells = [
    md_cell("""# 📊 Statistics Experiment 1: Exploratory Data Analysis & Descriptive Statistics
## CampusMind Academic Chatbot Query Log Analysis

### Objective
Perform comprehensive exploratory data analysis (EDA) on the response latency and confidence scores generated by the CampusMind RAG chatbot.
Calculate central tendency measures (mean, median, mode), dispersion measures (variance, standard deviation, IQR), and shape measures (skewness, kurtosis).
"""),
    code_cell("""import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt

# Generate representative latency data (in milliseconds)
np.random.seed(42)
rag_latency = np.random.normal(loc=350, scale=45, size=150)
cag_latency = np.random.normal(loc=8, scale=2, size=150)
combined_latency = np.concatenate([rag_latency, cag_latency])

df = pd.DataFrame({
    'latency_ms': combined_latency,
    'source': ['RAG'] * 150 + ['CAG'] * 150
})

print("Dataset Summary:")
print(df.head())
"""),
    md_cell("""### 1. Central Tendency & Dispersion Metrics
Mathematical formulations:
- Mean: $\\bar{x} = \\frac{1}{n} \\sum_{i=1}^n x_i$
- Sample Variance: $s^2 = \\frac{1}{n-1} \\sum_{i=1}^n (x_i - \\bar{x})^2$
- Sample Standard Deviation: $s = \\sqrt{s^2}$
- Skewness: $\\gamma_1 = \\frac{\\frac{1}{n} \\sum (x_i - \\bar{x})^3}{s^3}$
"""),
    code_cell("""mean_val = np.mean(df['latency_ms'])
median_val = np.median(df['latency_ms'])
std_val = np.std(df['latency_ms'], ddof=1)
skew_val = stats.skew(df['latency_ms'])
kurt_val = stats.kurtosis(df['latency_ms'])

print(f"Mean Latency: {mean_val:.2f} ms")
print(f"Median Latency: {median_val:.2f} ms")
print(f"Standard Deviation: {std_val:.2f} ms")
print(f"Skewness: {skew_val:.3f}")
print(f"Kurtosis: {kurt_val:.3f}")
"""),
    code_cell("""# Visualizing latency distributions
plt.figure(figsize=(10, 4))
plt.hist(rag_latency, bins=20, alpha=0.7, label='RAG (Vector Retrieval + LLM)', color='#7c3aed')
plt.hist(cag_latency, bins=15, alpha=0.7, label='CAG (Cache Augmented)', color='#06b6d4')
plt.title('CampusMind Query Latency Histogram')
plt.xlabel('Latency (ms)')
plt.ylabel('Frequency')
plt.legend()
plt.grid(True, alpha=0.2)
plt.show()
"""),
]

with open(os.path.join(NOTEBOOKS_DIR, "01_eda_descriptive_stats.ipynb"), "w", encoding="utf-8") as f:
    json.dump(make_notebook("EDA", nb1_cells), f, indent=2)


# -------------------------------------------------------------
# 2. 04_clt_sampling_distribution.ipynb
# -------------------------------------------------------------
nb4_cells = [
    md_cell("""# 🎲 Statistics Experiment 4: Central Limit Theorem (CLT) Simulation
## CampusMind Latency Sampling Distributions

### Objective
Demonstrate that the distribution of sample means approximates a Normal Distribution $\\mathcal{N}(\\mu, \\frac{\\sigma^2}{n})$ as the sample size $n$ increases, regardless of the underlying population distribution.
"""),
    code_cell("""import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

# Population: heavily skewed multi-modal response time distribution
np.random.seed(42)
pop = np.concatenate([
    np.random.exponential(scale=10, size=5000),   # Fast cache hits
    np.random.normal(loc=350, scale=40, size=5000) # RAG completions
])

# Sample sizes to test
sample_sizes = [2, 10, 30, 100]
num_samples = 1000

fig, axes = plt.subplots(1, 4, figsize=(16, 3.5))

for i, n in enumerate(sample_sizes):
    sample_means = [np.mean(np.random.choice(pop, size=n, replace=True)) for _ in range(num_samples)]
    axes[i].hist(sample_means, bins=25, density=True, alpha=0.7, color='#7c3aed')
    
    # Overlay theoretical normal distribution
    mu = np.mean(pop)
    sigma = np.std(pop) / np.sqrt(n)
    x = np.linspace(min(sample_means), max(sample_means), 100)
    axes[i].plot(x, stats.norm.pdf(x, mu, sigma), 'r--', lw=2)
    axes[i].set_title(f'Sample Size n = {n}')
    axes[i].set_xlabel('Sample Mean (ms)')

plt.suptitle('Demonstration of Central Limit Theorem on CampusMind Latency', y=1.05)
plt.tight_layout()
plt.show()
"""),
]

with open(os.path.join(NOTEBOOKS_DIR, "04_clt_sampling_distribution.ipynb"), "w", encoding="utf-8") as f:
    json.dump(make_notebook("CLT", nb4_cells), f, indent=2)


# -------------------------------------------------------------
# 3. 05_hypothesis_testing_rag_vs_cag.ipynb
# -------------------------------------------------------------
nb5_cells = [
    md_cell("""# 🧪 Statistics Experiment 5: Hypothesis Testing (A/B Test: RAG vs. CAG)
## Two-Sample Independent Welch's t-Test

### Objective
Formulate and test the hypothesis comparing the latency of the RAG pipeline versus the Cache-Augmented Generation (CAG) layer.

- **Null Hypothesis ($H_0$)**: $\\mu_{RAG} = \\mu_{CAG}$ (No significant latency difference).
- **Alternative Hypothesis ($H_1$)**: $\\mu_{RAG} > \\mu_{CAG}$ (CAG is statistically significantly faster).
- **Significance level ($\\alpha$)**: $0.05$.
"""),
    code_cell("""import numpy as np
import scipy.stats as stats

# Recorded query latencies (ms)
np.random.seed(42)
rag_times = np.random.normal(loc=345.5, scale=35.0, size=50)
cag_times = np.random.normal(loc=6.8, scale=1.5, size=50)

# Perform Welch's two-sample t-test (unequal variance)
t_stat, p_val = stats.ttest_ind(rag_times, cag_times, equal_var=False, alternative='greater')

print(f"RAG Mean Latency: {np.mean(rag_times):.2f} ms")
print(f"CAG Mean Latency: {np.mean(cag_times):.2f} ms")
print(f"Calculated t-statistic: {t_stat:.4f}")
print(f"P-value: {p_val:.4e}")

if p_val < 0.05:
    print("Conclusion: Reject H0! The CAG cache provides a statistically significant speedup (p < 0.05).")
else:
    print("Conclusion: Fail to reject H0.")
"""),
]

with open(os.path.join(NOTEBOOKS_DIR, "05_hypothesis_testing_rag_vs_cag.ipynb"), "w", encoding="utf-8") as f:
    json.dump(make_notebook("Hypothesis Testing", nb5_cells), f, indent=2)


# -------------------------------------------------------------
# 4. 08_regression_correlation.ipynb
# -------------------------------------------------------------
nb8_cells = [
    md_cell("""# 📈 Statistics Experiment 8 & 9: Pearson Correlation & Simple Linear Regression
## Modeling Response Latency as a Function of Prompt Length

### Objective
Determine the linear correlation $r$ and fit a regression line:
$$y = \\beta_1 x + \\beta_0$$
where $x$ is the prompt character length and $y$ is the Groq LPU completion time in milliseconds.
"""),
    code_cell("""import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats

np.random.seed(42)
prompt_lengths = np.random.uniform(20, 300, size=60)
# Latency model: base network RTT + token generation proportional to input
latency = 120 + 0.85 * prompt_lengths + np.random.normal(0, 15, size=60)

# Pearson correlation
r, p_val = stats.pearsonr(prompt_lengths, latency)
# Linear regression
slope, intercept, r_value, p_value, std_err = stats.linregress(prompt_lengths, latency)

print(f"Pearson Correlation (r): {r:.4f}")
print(f"Coefficient of Determination (R^2): {r**2:.4f}")
print(f"Regression Equation: y = {slope:.3f}x + {intercept:.3f}")

# Plot
plt.figure(figsize=(8, 5))
plt.scatter(prompt_lengths, latency, color='#06b6d4', alpha=0.8, label='Observed Queries')
plt.plot(prompt_lengths, slope * prompt_lengths + intercept, color='#7c3aed', lw=2, label='Fitted Line')
plt.title('Prompt Length vs. Response Latency Regression')
plt.xlabel('Prompt Character Length (chars)')
plt.ylabel('Latency (ms)')
plt.legend()
plt.grid(True, alpha=0.2)
plt.show()
"""),
]

with open(os.path.join(NOTEBOOKS_DIR, "08_regression_correlation.ipynb"), "w", encoding="utf-8") as f:
    json.dump(make_notebook("Regression", nb8_cells), f, indent=2)


# -------------------------------------------------------------
# 5. 12_pca_clustering.ipynb
# -------------------------------------------------------------
nb12_cells = [
    md_cell("""# 🔍 Statistics Experiment 12: Principal Component Analysis (PCA) & K-Means Clustering
## 2D Dimensionality Reduction of Query Embeddings

### Objective
Reduce 384-dimensional dense semantic vectors (from `all-MiniLM-L6-v2`) to 2 orthogonal principal components, and apply K-Means clustering to discover semantic topic groupings.
"""),
    code_cell("""import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# 3 synthetic clusters in 384-D vector space
np.random.seed(42)
c1 = np.random.normal(loc=0.5, scale=0.1, size=(25, 384))  # Academic / Algorithms
c2 = np.random.normal(loc=-0.5, scale=0.1, size=(25, 384)) # Admin / Timetable
c3 = np.random.normal(loc=0.0, scale=0.1, size=(25, 384))  # General greetings

X = np.vstack([c1, c2, c3])

# Apply PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)

# Apply KMeans
kmeans = KMeans(n_clusters=3, random_state=42)
labels = kmeans.fit_predict(X)

print(f"Explained Variance Ratio: PC1 = {pca.explained_variance_ratio_[0]:.3f}, PC2 = {pca.explained_variance_ratio_[1]:.3f}")

# Plot
plt.figure(figsize=(8, 5))
colors = ['#7c3aed', '#06b6d4', '#22c55e']
for k in range(3):
    plt.scatter(X_pca[labels == k, 0], X_pca[labels == k, 1], c=colors[k], label=f'Cluster {k+1}', s=60, alpha=0.8)

plt.title('2D PCA Projection & Clustering of CampusMind Queries')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.legend()
plt.grid(True, alpha=0.2)
plt.show()
"""),
]

with open(os.path.join(NOTEBOOKS_DIR, "12_pca_clustering.ipynb"), "w", encoding="utf-8") as f:
    json.dump(make_notebook("PCA", nb12_cells), f, indent=2)

print("All 5 Jupyter notebooks generated successfully in stats_notebooks/!")
