terraform {
  required_version = ">= 1.5.0"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
  }
}

provider "local" {}

resource "local_file" "backend_env" {
  content = <<-EOT
    # Generated by Terraform
    APP_NAME=${var.app_name}
    PORT=${var.port}
    ENVIRONMENT=${var.environment}
    GROQ_MODEL=${var.groq_model}
  EOT
  filename = "${path.module}/../../backend/.env.terraform"
}
